version: "3"
services:
  info_map_frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "4040:4040"
    depends_on:
      - info_map_backend
    restart: unless-stopped

  info_map_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "4444:4444"
    restart: unless-stopped
